### ISSUE TITLE
Still supported?

### ISSUE THREAD

**Issue by redhead** [ReactiveX/RxJavaDebug#10]
Is this project still applicable to current RxJava? Is there any alternative to debug RxJava?

It seems the projects is unmaintained and even RxJavaPlugins.getInstance() is deprecated.

**Comment by akarnokd** [comment]
I don't think so. This was not ported to support RxJava 2 and I don't really know what it is supposed to do. I guess you can check out RxJavaPlugins in 2.x and [RxJava2Extension's debug support](https://github.com/akarnokd/RxJava2Extensions#debug-support). See [Plugins](https://github.com/ReactiveX/RxJava/wiki/Plugins) for 1.x info.

**Comment by redhead** [comment]
Ah ok, I got here from an old article. I will look into the documentation. Thanks.
